name: Master-Windows

on:
  push:
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build on ${{ matrix.os }} on ${{ matrix.configuration }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        configuration: [Debug, Release]
        
    steps: 
      - name: Checkout repository
        uses: actions/checkout@v2.1.0
        with:
          submodules: recursive
     
      - name: Build
        uses: lukka/run-cmake@v2
        with:
          cmakeListsOrSettingsJson: CMakeListsTxtAdvanced 
          buildDirectory: ${{ github.workspace }}/build
          cmakeBuildType: ${{ matrix.configuration }} 
          cmakeAppendedArgs: -DENABLE_IPO:BOOL=True -DENABLE_TESTING:BOOL=True -DBUILD_SHARED_LIBS=TRUE 
          buildWithCMake: true
          cmakeGenerator: VS16Win64 
          buildWithCMakeArgs: -v --config ${{ matrix.configuration }} 
      
      - name: Test
        run: |
          cd build
          ctest -C ${{ matrix.configuration }}
      
      - name: install
        run: |
          cd build
          cmake --install . -v --prefix ../../install --config ${{ matrix.configuration }} 

      - name: Deploy
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.configuration }}_exports
          path: ${{ runner.workspace }}/install
          
      - name: Display deployment structure
        run: ls -R
        working-directory: ${{ runner.workspace }}/install  
